### ISSUE TITLE
Consulta ejercicio parcial

### ISSUE THREAD

**Issue by stefano-gentile** [facundoq/facundoq.github.io#1]
Hola profe, tengo una duda con este ejercicio que estuve haciendo y no sé si esta bien hecho el programa 
![img-20170921-wa0016](https://user-images.githubusercontent.com/26451058/31049176-eca93d08-a603-11e7-9c0e-71ed845f55f3.jpg)

El enunciado es 
Escribir un programa que encienda de a una led cada vez que se presione F10, inicialmente el led 7 debe estar encendido. Al presionar F10 debe apagarse y encenderse el led 6. Al presionar nuevamente F10 debe apagarse el 6 y encenderse el 5 y asi sucesivamente. El ciclo debe repetirse una vez alcanzado el led 0.

Espero tu respuesta

**Comment by facundoq** [comment]
El pa no se usa acá, el puerto B es el que está conectado a los leds. Entonces no hay que configurarlo

En la rutina de atención, no hay que apagar los leds. Directamente cambias de un patrón a otro.

El resto parece estar bien!
